export const MedicalSpecifications = {
  medical_spesification: {
    label: "Medical Specifications",
    values: [
      { code: "CARD", label: "Cardiology" },
      { code: "DERM", label: "Dermatology" },
      { code: "NEUR", label: "Neurology" },
      { code: "ORTH", label: "Orthopedics" },
      { code: "PSYC", label: "Psychiatry" },
      { code: "PED", label: "Pediatrics" },
      { code: "ONCO", label: "Oncology" },
      { code: "GYNE", label: "Gynecology" },
      { code: "ENT", label: "Otolaryngology (ENT)" },
      { code: "OPHTH", label: "Ophthalmology" },
      { code: "SURG", label: "General Surgery" },
      { code: "UROL", label: "Urology" },
      { code: "NEPH", label: "Nephrology" },
      { code: "GAST", label: "Gastroenterology" },
      { code: "ENDO", label: "Endocrinology" },
      { code: "HEMA", label: "Hematology" },
      { code: "IMM", label: "Immunology" },
      { code: "RHEU", label: "Rheumatology" },
      { code: "PULM", label: "Pulmonology" },
      { code: "ANES", label: "Anesthesiology" },
      { code: "EMER", label: "Emergency Medicine" },
      { code: "PATH", label: "Pathology" },
      { code: "RAD", label: "Radiology" },
      { code: "FAM", label: "Family Medicine" },
      { code: "INT", label: "Internal Medicine" },
      { code: "DENT", label: "Dentistry" },
      { code: "PSUR", label: "Plastic Surgery" },
      { code: "REHAB", label: "Rehabilitation Medicine" },
      { code: "NEON", label: "Neonatology" },
      { code: "GERI", label: "Geriatrics" },
      { code: "TROP", label: "Tropical Medicine" },
      { code: "NUCL", label: "Nuclear Medicine" },
      { code: "SPORT", label: "Sports Medicine" },
      { code: "OCCU", label: "Occupational Medicine" },
    ],
  },
};
